<?php
/**
 *
 *   Copyright © 2010-2017 by xhost.ch GmbH
 *
 *   All rights reserved.
 *
 **/
$itemlist = array(
'1:0'=>array('id'=>1,'data'=>0,'name'=>'Stone','item'=>'stone'),
'1:1'=>array('id'=>1,'data'=>1,'name'=>'Granite','item'=>'stone'),
'1:2'=>array('id'=>1,'data'=>2,'name'=>'Polished Granite','item'=>'stone'),
'1:3'=>array('id'=>1,'data'=>3,'name'=>'Diorite','item'=>'stone'),
'1:4'=>array('id'=>1,'data'=>4,'name'=>'Polished Diorite','item'=>'stone'),
'1:5'=>array('id'=>1,'data'=>5,'name'=>'Andesite','item'=>'stone'),
'1:6'=>array('id'=>1,'data'=>6,'name'=>'Polished Andesite','item'=>'stone'),
'2:0'=>array('id'=>2,'data'=>0,'name'=>'Grass','item'=>'grass'),
'3:0'=>array('id'=>3,'data'=>0,'name'=>'Dirt','item'=>'dirt'),
'3:1'=>array('id'=>3,'data'=>1,'name'=>'Coarse Dirt','item'=>'dirt'),
'3:2'=>array('id'=>3,'data'=>2,'name'=>'Podzol','item'=>'dirt'),
'4:0'=>array('id'=>4,'data'=>0,'name'=>'Cobblestone','item'=>'cobblestone'),
'5:0'=>array('id'=>5,'data'=>0,'name'=>'Oak Wood Plank','item'=>'planks'),
'5:1'=>array('id'=>5,'data'=>1,'name'=>'Spruce Wood Plank','item'=>'planks'),
'5:2'=>array('id'=>5,'data'=>2,'name'=>'Birch Wood Plank','item'=>'planks'),
'5:3'=>array('id'=>5,'data'=>3,'name'=>'Jungle Wood Plank','item'=>'planks'),
'5:4'=>array('id'=>5,'data'=>4,'name'=>'Acacia Wood Plank','item'=>'planks'),
'5:5'=>array('id'=>5,'data'=>5,'name'=>'Dark Oak Wood Plank','item'=>'planks'),
'6:0'=>array('id'=>6,'data'=>0,'name'=>'Oak Sapling','item'=>'sapling'),
'6:1'=>array('id'=>6,'data'=>1,'name'=>'Spruce Sapling','item'=>'sapling'),
'6:2'=>array('id'=>6,'data'=>2,'name'=>'Birch Sapling','item'=>'sapling'),
'6:3'=>array('id'=>6,'data'=>3,'name'=>'Jungle Sapling','item'=>'sapling'),
'6:4'=>array('id'=>6,'data'=>4,'name'=>'Acacia Sapling','item'=>'sapling'),
'6:5'=>array('id'=>6,'data'=>5,'name'=>'Dark Oak Sapling','item'=>'sapling'),
'7:0'=>array('id'=>7,'data'=>0,'name'=>'Bedrock','item'=>'bedrock'),
'8:0'=>array('id'=>8,'data'=>0,'name'=>'Flowing Water','item'=>'flowing_water'),
'9:0'=>array('id'=>9,'data'=>0,'name'=>'Still Water','item'=>'water'),
'10:0'=>array('id'=>10,'data'=>0,'name'=>'Flowing Lava','item'=>'flowing_lava'),
'11:0'=>array('id'=>11,'data'=>0,'name'=>'Still Lava','item'=>'lava'),
'12:0'=>array('id'=>12,'data'=>0,'name'=>'Sand','item'=>'sand'),
'12:1'=>array('id'=>12,'data'=>1,'name'=>'Red Sand','item'=>'sand'),
'13:0'=>array('id'=>13,'data'=>0,'name'=>'Gravel','item'=>'gravel'),
'14:0'=>array('id'=>14,'data'=>0,'name'=>'Gold Ore','item'=>'gold_ore'),
'15:0'=>array('id'=>15,'data'=>0,'name'=>'Iron Ore','item'=>'iron_ore'),
'16:0'=>array('id'=>16,'data'=>0,'name'=>'Coal Ore','item'=>'coal_ore'),
'17:0'=>array('id'=>17,'data'=>0,'name'=>'Oak Wood','item'=>'log'),
'17:1'=>array('id'=>17,'data'=>1,'name'=>'Spruce Wood','item'=>'log'),
'17:2'=>array('id'=>17,'data'=>2,'name'=>'Birch Wood','item'=>'log'),
'17:3'=>array('id'=>17,'data'=>3,'name'=>'Jungle Wood','item'=>'log'),
'18:0'=>array('id'=>18,'data'=>0,'name'=>'Oak Leaves','item'=>'leaves'),
'18:1'=>array('id'=>18,'data'=>1,'name'=>'Spruce Leaves','item'=>'leaves'),
'18:2'=>array('id'=>18,'data'=>2,'name'=>'Birch Leaves','item'=>'leaves'),
'18:3'=>array('id'=>18,'data'=>3,'name'=>'Jungle Leaves','item'=>'leaves'),
'19:0'=>array('id'=>19,'data'=>0,'name'=>'Sponge','item'=>'sponge'),
'19:1'=>array('id'=>19,'data'=>1,'name'=>'Wet Sponge','item'=>'sponge'),
'20:0'=>array('id'=>20,'data'=>0,'name'=>'Glass','item'=>'glass'),
'21:0'=>array('id'=>21,'data'=>0,'name'=>'Lapis Lazuli Ore','item'=>'lapis_ore'),
'22:0'=>array('id'=>22,'data'=>0,'name'=>'Lapis Lazuli Block','item'=>'lapis_block'),
'23:0'=>array('id'=>23,'data'=>0,'name'=>'Dispenser','item'=>'dispenser'),
'24:0'=>array('id'=>24,'data'=>0,'name'=>'Sandstone','item'=>'sandstone'),
'24:1'=>array('id'=>24,'data'=>1,'name'=>'Chiseled Sandstone','item'=>'sandstone'),
'24:2'=>array('id'=>24,'data'=>2,'name'=>'Smooth Sandstone','item'=>'sandstone'),
'25:0'=>array('id'=>25,'data'=>0,'name'=>'Note Block','item'=>'noteblock'),
'26:0'=>array('id'=>26,'data'=>0,'name'=>'Bed','item'=>'bed'),
'27:0'=>array('id'=>27,'data'=>0,'name'=>'Powered Rail','item'=>'golden_rail'),
'28:0'=>array('id'=>28,'data'=>0,'name'=>'Detector Rail','item'=>'detector_rail'),
'29:0'=>array('id'=>29,'data'=>0,'name'=>'Sticky Piston','item'=>'sticky_piston'),
'30:0'=>array('id'=>30,'data'=>0,'name'=>'Cobweb','item'=>'web'),
'31:0'=>array('id'=>31,'data'=>0,'name'=>'Dead Shrub','item'=>'tallgrass'),
'31:1'=>array('id'=>31,'data'=>1,'name'=>'Grass','item'=>'tallgrass'),
'31:2'=>array('id'=>31,'data'=>2,'name'=>'Fern','item'=>'tallgrass'),
'32:0'=>array('id'=>32,'data'=>0,'name'=>'Dead Shrub','item'=>'deadbush'),
'33:0'=>array('id'=>33,'data'=>0,'name'=>'Piston','item'=>'piston'),
'34:0'=>array('id'=>34,'data'=>0,'name'=>'Piston Head','item'=>'piston_head'),
'35:0'=>array('id'=>35,'data'=>0,'name'=>'White Wool','item'=>'wool'),
'35:1'=>array('id'=>35,'data'=>1,'name'=>'Orange Wool','item'=>'wool'),
'35:2'=>array('id'=>35,'data'=>2,'name'=>'Magenta Wool','item'=>'wool'),
'35:3'=>array('id'=>35,'data'=>3,'name'=>'Light Blue Wool','item'=>'wool'),
'35:4'=>array('id'=>35,'data'=>4,'name'=>'Yellow Wool','item'=>'wool'),
'35:5'=>array('id'=>35,'data'=>5,'name'=>'Lime Wool','item'=>'wool'),
'35:6'=>array('id'=>35,'data'=>6,'name'=>'Pink Wool','item'=>'wool'),
'35:7'=>array('id'=>35,'data'=>7,'name'=>'Gray Wool','item'=>'wool'),
'35:8'=>array('id'=>35,'data'=>8,'name'=>'Light Gray Wool','item'=>'wool'),
'35:9'=>array('id'=>35,'data'=>9,'name'=>'Cyan Wool','item'=>'wool'),
'35:10'=>array('id'=>35,'data'=>10,'name'=>'Purple Wool','item'=>'wool'),
'35:11'=>array('id'=>35,'data'=>11,'name'=>'Blue Wool','item'=>'wool'),
'35:12'=>array('id'=>35,'data'=>12,'name'=>'Brown Wool','item'=>'wool'),
'35:13'=>array('id'=>35,'data'=>13,'name'=>'Green Wool','item'=>'wool'),
'35:14'=>array('id'=>35,'data'=>14,'name'=>'Red Wool','item'=>'wool'),
'35:15'=>array('id'=>35,'data'=>15,'name'=>'Black Wool','item'=>'wool'),
'37:0'=>array('id'=>37,'data'=>0,'name'=>'Dandelion','item'=>'yellow_flower'),
'38:0'=>array('id'=>38,'data'=>0,'name'=>'Poppy','item'=>'red_flower'),
'38:1'=>array('id'=>38,'data'=>1,'name'=>'Blue Orchid','item'=>'red_flower'),
'38:2'=>array('id'=>38,'data'=>2,'name'=>'Allium','item'=>'red_flower'),
'38:3'=>array('id'=>38,'data'=>3,'name'=>'Azure Bluet','item'=>'red_flower'),
'38:4'=>array('id'=>38,'data'=>4,'name'=>'Red Tulip','item'=>'red_flower'),
'38:5'=>array('id'=>38,'data'=>5,'name'=>'Orange Tulip','item'=>'red_flower'),
'38:6'=>array('id'=>38,'data'=>6,'name'=>'White Tulip','item'=>'red_flower'),
'38:7'=>array('id'=>38,'data'=>7,'name'=>'Pink Tulip','item'=>'red_flower'),
'38:8'=>array('id'=>38,'data'=>8,'name'=>'Oxeye Daisy','item'=>'red_flower'),
'39:0'=>array('id'=>39,'data'=>0,'name'=>'Brown Mushroom','item'=>'brown_mushroom'),
'40:0'=>array('id'=>40,'data'=>0,'name'=>'Red Mushroom','item'=>'red_mushroom'),
'41:0'=>array('id'=>41,'data'=>0,'name'=>'Gold Block','item'=>'gold_block'),
'42:0'=>array('id'=>42,'data'=>0,'name'=>'Iron Block','item'=>'iron_block'),
'43:0'=>array('id'=>43,'data'=>0,'name'=>'Double Stone Slab','item'=>'double_stone_slab'),
'43:1'=>array('id'=>43,'data'=>1,'name'=>'Double Sandstone Slab','item'=>'double_stone_slab'),
'43:2'=>array('id'=>43,'data'=>2,'name'=>'Double Wooden Slab','item'=>'double_stone_slab'),
'43:3'=>array('id'=>43,'data'=>3,'name'=>'Double Cobblestone Slab','item'=>'double_stone_slab'),
'43:4'=>array('id'=>43,'data'=>4,'name'=>'Double Brick Slab','item'=>'double_stone_slab'),
'43:5'=>array('id'=>43,'data'=>5,'name'=>'Double Stone Brick Slab','item'=>'double_stone_slab'),
'43:6'=>array('id'=>43,'data'=>6,'name'=>'Double Nether Brick Slab','item'=>'double_stone_slab'),
'43:7'=>array('id'=>43,'data'=>7,'name'=>'Double Quartz Slab','item'=>'double_stone_slab'),
'44:0'=>array('id'=>44,'data'=>0,'name'=>'Stone Slab','item'=>'stone_slab'),
'44:1'=>array('id'=>44,'data'=>1,'name'=>'Sandstone Slab','item'=>'stone_slab'),
'44:2'=>array('id'=>44,'data'=>2,'name'=>'Wooden Slab','item'=>'stone_slab'),
'44:3'=>array('id'=>44,'data'=>3,'name'=>'Cobblestone Slab','item'=>'stone_slab'),
'44:4'=>array('id'=>44,'data'=>4,'name'=>'Brick Slab','item'=>'stone_slab'),
'44:5'=>array('id'=>44,'data'=>5,'name'=>'Stone Brick Slab','item'=>'stone_slab'),
'44:6'=>array('id'=>44,'data'=>6,'name'=>'Nether Brick Slab','item'=>'stone_slab'),
'44:7'=>array('id'=>44,'data'=>7,'name'=>'Quartz Slab','item'=>'stone_slab'),
'45:0'=>array('id'=>45,'data'=>0,'name'=>'Bricks','item'=>'brick_block'),
'46:0'=>array('id'=>46,'data'=>0,'name'=>'TNT','item'=>'tnt'),
'47:0'=>array('id'=>47,'data'=>0,'name'=>'Bookshelf','item'=>'bookshelf'),
'48:0'=>array('id'=>48,'data'=>0,'name'=>'Moss Stone','item'=>'mossy_cobblestone'),
'49:0'=>array('id'=>49,'data'=>0,'name'=>'Obsidian','item'=>'obsidian'),
'50:0'=>array('id'=>50,'data'=>0,'name'=>'Torch','item'=>'torch'),
'51:0'=>array('id'=>51,'data'=>0,'name'=>'Fire','item'=>'fire'),
'52:0'=>array('id'=>52,'data'=>0,'name'=>'Monster Spawner','item'=>'mob_spawner'),
'53:0'=>array('id'=>53,'data'=>0,'name'=>'Oak Wood Stairs','item'=>'oak_stairs'),
'54:0'=>array('id'=>54,'data'=>0,'name'=>'Chest','item'=>'chest'),
'55:0'=>array('id'=>55,'data'=>0,'name'=>'Redstone Wire','item'=>'redstone_wire'),
'56:0'=>array('id'=>56,'data'=>0,'name'=>'Diamond Ore','item'=>'diamond_ore'),
'57:0'=>array('id'=>57,'data'=>0,'name'=>'Diamond Block','item'=>'diamond_block'),
'58:0'=>array('id'=>58,'data'=>0,'name'=>'Crafting Table','item'=>'crafting_table'),
'59:0'=>array('id'=>59,'data'=>0,'name'=>'Wheat Crops','item'=>'wheat'),
'60:0'=>array('id'=>60,'data'=>0,'name'=>'Farmland','item'=>'farmland'),
'61:0'=>array('id'=>61,'data'=>0,'name'=>'Furnace','item'=>'furnace'),
'62:0'=>array('id'=>62,'data'=>0,'name'=>'Burning Furnace','item'=>'lit_furnace'),
'63:0'=>array('id'=>63,'data'=>0,'name'=>'Standing Sign Block','item'=>'standing_sign'),
'64:0'=>array('id'=>64,'data'=>0,'name'=>'Oak Door Block','item'=>'wooden_door'),
'65:0'=>array('id'=>65,'data'=>0,'name'=>'Ladder','item'=>'ladder'),
'66:0'=>array('id'=>66,'data'=>0,'name'=>'Rail','item'=>'rail'),
'67:0'=>array('id'=>67,'data'=>0,'name'=>'Cobblestone Stairs','item'=>'stone_stairs'),
'68:0'=>array('id'=>68,'data'=>0,'name'=>'Wall-mounted Sign Block','item'=>'wall_sign'),
'69:0'=>array('id'=>69,'data'=>0,'name'=>'Lever','item'=>'lever'),
'70:0'=>array('id'=>70,'data'=>0,'name'=>'Stone Pressure Plate','item'=>'stone_pressure_plate'),
'71:0'=>array('id'=>71,'data'=>0,'name'=>'Iron Door Block','item'=>'iron_door'),
'72:0'=>array('id'=>72,'data'=>0,'name'=>'Wooden Pressure Plate','item'=>'wooden_pressure_plate'),
'73:0'=>array('id'=>73,'data'=>0,'name'=>'Redstone Ore','item'=>'redstone_ore'),
'74:0'=>array('id'=>74,'data'=>0,'name'=>'Glowing Redstone Ore','item'=>'lit_redstone_ore'),
'75:0'=>array('id'=>75,'data'=>0,'name'=>'Redstone Torch (off)','item'=>'unlit_redstone_torch'),
'76:0'=>array('id'=>76,'data'=>0,'name'=>'Redstone Torch (on)','item'=>'redstone_torch'),
'77:0'=>array('id'=>77,'data'=>0,'name'=>'Stone Button','item'=>'stone_button'),
'78:0'=>array('id'=>78,'data'=>0,'name'=>'Snow','item'=>'snow_layer'),
'79:0'=>array('id'=>79,'data'=>0,'name'=>'Ice','item'=>'ice'),
'80:0'=>array('id'=>80,'data'=>0,'name'=>'Snow Block','item'=>'snow'),
'81:0'=>array('id'=>81,'data'=>0,'name'=>'Cactus','item'=>'cactus'),
'82:0'=>array('id'=>82,'data'=>0,'name'=>'Clay','item'=>'clay'),
'83:0'=>array('id'=>83,'data'=>0,'name'=>'Sugar Canes','item'=>'reeds'),
'84:0'=>array('id'=>84,'data'=>0,'name'=>'Jukebox','item'=>'jukebox'),
'85:0'=>array('id'=>85,'data'=>0,'name'=>'Oak Fence','item'=>'fence'),
'86:0'=>array('id'=>86,'data'=>0,'name'=>'Pumpkin','item'=>'pumpkin'),
'87:0'=>array('id'=>87,'data'=>0,'name'=>'Netherrack','item'=>'netherrack'),
'88:0'=>array('id'=>88,'data'=>0,'name'=>'Soul Sand','item'=>'soul_sand'),
'89:0'=>array('id'=>89,'data'=>0,'name'=>'Glowstone','item'=>'glowstone'),
'90:0'=>array('id'=>90,'data'=>0,'name'=>'Nether Portal','item'=>'portal'),
'91:0'=>array('id'=>91,'data'=>0,'name'=>'Jack o\'Lantern','item'=>'lit_pumpkin'),
'92:0'=>array('id'=>92,'data'=>0,'name'=>'Cake Block','item'=>'cake'),
'93:0'=>array('id'=>93,'data'=>0,'name'=>'Redstone Repeater Block (off)','item'=>'unpowered_repeater'),
'94:0'=>array('id'=>94,'data'=>0,'name'=>'Redstone Repeater Block (on)','item'=>'powered_repeater'),
'95:0'=>array('id'=>95,'data'=>0,'name'=>'White Stained Glass','item'=>'stained_glass'),
'95:1'=>array('id'=>95,'data'=>1,'name'=>'Orange Stained Glass','item'=>'stained_glass'),
'95:2'=>array('id'=>95,'data'=>2,'name'=>'Magenta Stained Glass','item'=>'stained_glass'),
'95:3'=>array('id'=>95,'data'=>3,'name'=>'Light Blue Stained Glass','item'=>'stained_glass'),
'95:4'=>array('id'=>95,'data'=>4,'name'=>'Yellow Stained Glass','item'=>'stained_glass'),
'95:5'=>array('id'=>95,'data'=>5,'name'=>'Lime Stained Glass','item'=>'stained_glass'),
'95:6'=>array('id'=>95,'data'=>6,'name'=>'Pink Stained Glass','item'=>'stained_glass'),
'95:7'=>array('id'=>95,'data'=>7,'name'=>'Gray Stained Glass','item'=>'stained_glass'),
'95:8'=>array('id'=>95,'data'=>8,'name'=>'Light Gray Stained Glass','item'=>'stained_glass'),
'95:9'=>array('id'=>95,'data'=>9,'name'=>'Cyan Stained Glass','item'=>'stained_glass'),
'95:10'=>array('id'=>95,'data'=>10,'name'=>'Purple Stained Glass','item'=>'stained_glass'),
'95:11'=>array('id'=>95,'data'=>11,'name'=>'Blue Stained Glass','item'=>'stained_glass'),
'95:12'=>array('id'=>95,'data'=>12,'name'=>'Brown Stained Glass','item'=>'stained_glass'),
'95:13'=>array('id'=>95,'data'=>13,'name'=>'Green Stained Glass','item'=>'stained_glass'),
'95:14'=>array('id'=>95,'data'=>14,'name'=>'Red Stained Glass','item'=>'stained_glass'),
'95:15'=>array('id'=>95,'data'=>15,'name'=>'Black Stained Glass','item'=>'stained_glass'),
'96:0'=>array('id'=>96,'data'=>0,'name'=>'Wooden Trapdoor','item'=>'trapdoor'),
'97:0'=>array('id'=>97,'data'=>0,'name'=>'Stone Monster Egg','item'=>'monster_egg'),
'97:1'=>array('id'=>97,'data'=>1,'name'=>'Cobblestone Monster Egg','item'=>'monster_egg'),
'97:2'=>array('id'=>97,'data'=>2,'name'=>'Stone Brick Monster Egg','item'=>'monster_egg'),
'97:3'=>array('id'=>97,'data'=>3,'name'=>'Mossy Stone Brick Monster Egg','item'=>'monster_egg'),
'97:4'=>array('id'=>97,'data'=>4,'name'=>'Cracked Stone Brick Monster Egg','item'=>'monster_egg'),
'97:5'=>array('id'=>97,'data'=>5,'name'=>'Chiseled Stone Brick Monster Egg','item'=>'monster_egg'),
'98:0'=>array('id'=>98,'data'=>0,'name'=>'Stone Bricks','item'=>'stonebrick'),
'98:1'=>array('id'=>98,'data'=>1,'name'=>'Mossy Stone Bricks','item'=>'stonebrick'),
'98:2'=>array('id'=>98,'data'=>2,'name'=>'Cracked Stone Bricks','item'=>'stonebrick'),
'98:3'=>array('id'=>98,'data'=>3,'name'=>'Chiseled Stone Bricks','item'=>'stonebrick'),
'99:0'=>array('id'=>99,'data'=>0,'name'=>'Red Mushroom Cap','item'=>'stonebrick'),
'100:0'=>array('id'=>100,'data'=>0,'name'=>'Brown Mushroom Cap','item'=>'stonebrick'),
'101:0'=>array('id'=>101,'data'=>0,'name'=>'Iron Bars','item'=>'iron_bars'),
'102:0'=>array('id'=>102,'data'=>0,'name'=>'Glass Pane','item'=>'glass_pane'),
'103:0'=>array('id'=>103,'data'=>0,'name'=>'Melon Block','item'=>'melon_block'),
'104:0'=>array('id'=>104,'data'=>0,'name'=>'Pumpkin Stem','item'=>'pumpkin_stem'),
'105:0'=>array('id'=>105,'data'=>0,'name'=>'Melon Stem','item'=>'melon_stem'),
'106:0'=>array('id'=>106,'data'=>0,'name'=>'Vines','item'=>'vine'),
'107:0'=>array('id'=>107,'data'=>0,'name'=>'Oak Fence Gate','item'=>'fence_gate'),
'108:0'=>array('id'=>108,'data'=>0,'name'=>'Brick Stairs','item'=>'brick_stairs'),
'109:0'=>array('id'=>109,'data'=>0,'name'=>'Stone Brick Stairs','item'=>'stone_brick_stairs'),
'110:0'=>array('id'=>110,'data'=>0,'name'=>'Mycelium','item'=>'mycelium'),
'111:0'=>array('id'=>111,'data'=>0,'name'=>'Lily Pad','item'=>'waterlily'),
'112:0'=>array('id'=>112,'data'=>0,'name'=>'Nether Brick','item'=>'nether_brick'),
'113:0'=>array('id'=>113,'data'=>0,'name'=>'Nether Brick Fence','item'=>'nether_brick_fence'),
'114:0'=>array('id'=>114,'data'=>0,'name'=>'Nether Brick Stairs','item'=>'nether_brick_stairs'),
'115:0'=>array('id'=>115,'data'=>0,'name'=>'Nether Wart','item'=>'nether_wart'),
'116:0'=>array('id'=>116,'data'=>0,'name'=>'Enchantment Table','item'=>'enchanting_table'),
'117:0'=>array('id'=>117,'data'=>0,'name'=>'Brewing Stand','item'=>'brewing_stand'),
'118:0'=>array('id'=>118,'data'=>0,'name'=>'Cauldron','item'=>'cauldron'),
'119:0'=>array('id'=>119,'data'=>0,'name'=>'End Portal','item'=>'end_portal'),
'120:0'=>array('id'=>120,'data'=>0,'name'=>'End Portal Frame','item'=>'end_portal_frame'),
'121:0'=>array('id'=>121,'data'=>0,'name'=>'End Stone','item'=>'end_stone'),
'122:0'=>array('id'=>122,'data'=>0,'name'=>'Dragon Egg','item'=>'dragon_egg'),
'123:0'=>array('id'=>123,'data'=>0,'name'=>'Redstone Lamp (inactive)','item'=>'redstone_lamp'),
'124:0'=>array('id'=>124,'data'=>0,'name'=>'Redstone Lamp (active)','item'=>'lit_redstone_lamp'),
'125:0'=>array('id'=>125,'data'=>0,'name'=>'Double Oak Wood Slab','item'=>'double_wooden_slab'),
'125:1'=>array('id'=>125,'data'=>1,'name'=>'Double Spruce Wood Slab','item'=>'double_wooden_slab'),
'125:2'=>array('id'=>125,'data'=>2,'name'=>'Double Birch Wood Slab','item'=>'double_wooden_slab'),
'125:3'=>array('id'=>125,'data'=>3,'name'=>'Double Jungle Wood Slab','item'=>'double_wooden_slab'),
'125:4'=>array('id'=>125,'data'=>4,'name'=>'Double Acacia Wood Slab','item'=>'double_wooden_slab'),
'125:5'=>array('id'=>125,'data'=>5,'name'=>'Double Dark Oak Wood Slab','item'=>'double_wooden_slab'),
'126:0'=>array('id'=>126,'data'=>0,'name'=>'Oak Wood Slab','item'=>'wooden_slab'),
'126:1'=>array('id'=>126,'data'=>1,'name'=>'Spruce Wood Slab','item'=>'wooden_slab'),
'126:2'=>array('id'=>126,'data'=>2,'name'=>'Birch Wood Slab','item'=>'wooden_slab'),
'126:3'=>array('id'=>126,'data'=>3,'name'=>'Jungle Wood Slab','item'=>'wooden_slab'),
'126:4'=>array('id'=>126,'data'=>4,'name'=>'Acacia Wood Slab','item'=>'wooden_slab'),
'126:5'=>array('id'=>126,'data'=>5,'name'=>'Dark Oak Wood Slab','item'=>'wooden_slab'),
'127:0'=>array('id'=>127,'data'=>0,'name'=>'Cocoa','item'=>'cocoa'),
'128:0'=>array('id'=>128,'data'=>0,'name'=>'Sandstone Stairs','item'=>'sandstone_stairs'),
'129:0'=>array('id'=>129,'data'=>0,'name'=>'Emerald Ore','item'=>'emerald_ore'),
'130:0'=>array('id'=>130,'data'=>0,'name'=>'Ender Chest','item'=>'ender_chest'),
'131:0'=>array('id'=>131,'data'=>0,'name'=>'Tripwire Hook','item'=>'tripwire_hook'),
'132:0'=>array('id'=>132,'data'=>0,'name'=>'Tripwire','item'=>'tripwire_hook'),
'133:0'=>array('id'=>133,'data'=>0,'name'=>'Emerald Block','item'=>'emerald_block'),
'134:0'=>array('id'=>134,'data'=>0,'name'=>'Spruce Wood Stairs','item'=>'spruce_stairs'),
'135:0'=>array('id'=>135,'data'=>0,'name'=>'Birch Wood Stairs','item'=>'birch_stairs'),
'136:0'=>array('id'=>136,'data'=>0,'name'=>'Jungle Wood Stairs','item'=>'jungle_stairs'),
'137:0'=>array('id'=>137,'data'=>0,'name'=>'Command Block','item'=>'command_block'),
'138:0'=>array('id'=>138,'data'=>0,'name'=>'Beacon','item'=>'beacon'),
'139:0'=>array('id'=>139,'data'=>0,'name'=>'Cobblestone Wall','item'=>'cobblestone_wall'),
'139:1'=>array('id'=>139,'data'=>1,'name'=>'Mossy Cobblestone Wall','item'=>'cobblestone_wall'),
'140:0'=>array('id'=>140,'data'=>0,'name'=>'Flower Pot','item'=>'flower_pot'),
'141:0'=>array('id'=>141,'data'=>0,'name'=>'Carrots','item'=>'carrots'),
'142:0'=>array('id'=>142,'data'=>0,'name'=>'Potatoes','item'=>'potatoes'),
'143:0'=>array('id'=>143,'data'=>0,'name'=>'Wooden Button','item'=>'wooden_button'),
'144:0'=>array('id'=>144,'data'=>0,'name'=>'Mob Head','item'=>'skull'),
'145:0'=>array('id'=>145,'data'=>0,'name'=>'Anvil','item'=>'anvil'),
'146:0'=>array('id'=>146,'data'=>0,'name'=>'Trapped Chest','item'=>'trapped_chest'),
'147:0'=>array('id'=>147,'data'=>0,'name'=>'Weighted Pressure Plate (light)','item'=>'light_weighted_pressure_plate'),
'148:0'=>array('id'=>148,'data'=>0,'name'=>'Weighted Pressure Plate (heavy)','item'=>'heavy_weighted_pressure_plate'),
'149:0'=>array('id'=>149,'data'=>0,'name'=>'Redstone Comparator (inactive)','item'=>'unpowered_comparator'),
'150:0'=>array('id'=>150,'data'=>0,'name'=>'Redstone Comparator (active)','item'=>'powered_comparator'),
'151:0'=>array('id'=>151,'data'=>0,'name'=>'Daylight Sensor','item'=>'daylight_detector'),
'152:0'=>array('id'=>152,'data'=>0,'name'=>'Redstone Block','item'=>'redstone_block'),
'153:0'=>array('id'=>153,'data'=>0,'name'=>'Nether Quartz Ore','item'=>'quartz_ore'),
'154:0'=>array('id'=>154,'data'=>0,'name'=>'Hopper','item'=>'hopper'),
'155:0'=>array('id'=>155,'data'=>0,'name'=>'Quartz Block','item'=>'quartz_block'),
'155:1'=>array('id'=>155,'data'=>1,'name'=>'Chiseled Quartz Block','item'=>'quartz_block'),
'155:2'=>array('id'=>155,'data'=>2,'name'=>'Pillar Quartz Block','item'=>'quartz_block'),
'156:0'=>array('id'=>156,'data'=>0,'name'=>'Quartz Stairs','item'=>'quartz_stairs'),
'157:0'=>array('id'=>157,'data'=>0,'name'=>'Activator Rail','item'=>'activator_rail'),
'158:0'=>array('id'=>158,'data'=>0,'name'=>'Dropper','item'=>'dropper'),
'159:0'=>array('id'=>159,'data'=>0,'name'=>'White Stained Clay','item'=>'stained_hardened_clay'),
'159:1'=>array('id'=>159,'data'=>1,'name'=>'Orange Stained Clay','item'=>'stained_hardened_clay'),
'159:2'=>array('id'=>159,'data'=>2,'name'=>'Magenta Stained Clay','item'=>'stained_hardened_clay'),
'159:3'=>array('id'=>159,'data'=>3,'name'=>'Light Blue Stained Clay','item'=>'stained_hardened_clay'),
'159:4'=>array('id'=>159,'data'=>4,'name'=>'Yellow Stained Clay','item'=>'stained_hardened_clay'),
'159:5'=>array('id'=>159,'data'=>5,'name'=>'Lime Stained Clay','item'=>'stained_hardened_clay'),
'159:6'=>array('id'=>159,'data'=>6,'name'=>'Pink Stained Clay','item'=>'stained_hardened_clay'),
'159:7'=>array('id'=>159,'data'=>7,'name'=>'Gray Stained Clay','item'=>'stained_hardened_clay'),
'159:8'=>array('id'=>159,'data'=>8,'name'=>'Light Gray Stained Clay','item'=>'stained_hardened_clay'),
'159:9'=>array('id'=>159,'data'=>9,'name'=>'Cyan Stained Clay','item'=>'stained_hardened_clay'),
'159:10'=>array('id'=>159,'data'=>10,'name'=>'Purple Stained Clay','item'=>'stained_hardened_clay'),
'159:11'=>array('id'=>159,'data'=>11,'name'=>'Blue Stained Clay','item'=>'stained_hardened_clay'),
'159:12'=>array('id'=>159,'data'=>12,'name'=>'Brown Stained Clay','item'=>'stained_hardened_clay'),
'159:13'=>array('id'=>159,'data'=>13,'name'=>'Green Stained Clay','item'=>'stained_hardened_clay'),
'159:14'=>array('id'=>159,'data'=>14,'name'=>'Red Stained Clay','item'=>'stained_hardened_clay'),
'159:15'=>array('id'=>159,'data'=>15,'name'=>'Black Stained Clay','item'=>'stained_hardened_clay'),
'160:0'=>array('id'=>160,'data'=>0,'name'=>'White Stained Glass Pane','item'=>'stained_glass_pane'),
'160:1'=>array('id'=>160,'data'=>1,'name'=>'Orange Stained Glass Pane','item'=>'stained_glass_pane'),
'160:2'=>array('id'=>160,'data'=>2,'name'=>'Magenta Stained Glass Pane','item'=>'stained_glass_pane'),
'160:3'=>array('id'=>160,'data'=>3,'name'=>'Light Blue Stained Glass Pane','item'=>'stained_glass_pane'),
'160:4'=>array('id'=>160,'data'=>4,'name'=>'Yellow Stained Glass Pane','item'=>'stained_glass_pane'),
'160:5'=>array('id'=>160,'data'=>5,'name'=>'Lime Stained Glass Pane','item'=>'stained_glass_pane'),
'160:6'=>array('id'=>160,'data'=>6,'name'=>'Pink Stained Glass Pane','item'=>'stained_glass_pane'),
'160:7'=>array('id'=>160,'data'=>7,'name'=>'Gray Stained Glass Pane','item'=>'stained_glass_pane'),
'160:8'=>array('id'=>160,'data'=>8,'name'=>'Light Gray Stained Glass Pane','item'=>'stained_glass_pane'),
'160:9'=>array('id'=>160,'data'=>9,'name'=>'Cyan Stained Glass Pane','item'=>'stained_glass_pane'),
'160:10'=>array('id'=>160,'data'=>10,'name'=>'Purple Stained Glass Pane','item'=>'stained_glass_pane'),
'160:11'=>array('id'=>160,'data'=>11,'name'=>'Blue Stained Glass Pane','item'=>'stained_glass_pane'),
'160:12'=>array('id'=>160,'data'=>12,'name'=>'Brown Stained Glass Pane','item'=>'stained_glass_pane'),
'160:13'=>array('id'=>160,'data'=>13,'name'=>'Green Stained Glass Pane','item'=>'stained_glass_pane'),
'160:14'=>array('id'=>160,'data'=>14,'name'=>'Red Stained Glass Pane','item'=>'stained_glass_pane'),
'160:15'=>array('id'=>160,'data'=>15,'name'=>'Black Stained Glass Pane','item'=>'stained_glass_pane'),
'161:0'=>array('id'=>161,'data'=>0,'name'=>'Acacia Leaves','item'=>'leaves2'),
'161:1'=>array('id'=>161,'data'=>1,'name'=>'Dark Oak Leaves','item'=>'leaves2'),
'162:0'=>array('id'=>162,'data'=>0,'name'=>'Acacia Wood','item'=>'logs2'),
'162:1'=>array('id'=>162,'data'=>1,'name'=>'Dark Oak Wood','item'=>'logs2'),
'163:0'=>array('id'=>163,'data'=>0,'name'=>'Acacia Wood Stairs','item'=>'acacia_stairs'),
'164:0'=>array('id'=>164,'data'=>0,'name'=>'Dark Oak Wood Stairs','item'=>'dark_oak_stairs'),
'165:0'=>array('id'=>165,'data'=>0,'name'=>'Slime Block','item'=>'slime'),
'166:0'=>array('id'=>166,'data'=>0,'name'=>'Barrier','item'=>'barrier'),
'167:0'=>array('id'=>167,'data'=>0,'name'=>'Iron Trapdoor','item'=>'iron_trapdoor'),
'168:0'=>array('id'=>168,'data'=>0,'name'=>'Prismarine','item'=>'prismarine'),
'168:1'=>array('id'=>168,'data'=>1,'name'=>'Prismarine Bricks','item'=>'prismarine'),
'168:2'=>array('id'=>168,'data'=>2,'name'=>'Dark Prismarine','item'=>'prismarine'),
'169:0'=>array('id'=>169,'data'=>0,'name'=>'Sea Lantern','item'=>'sea_lantern'),
'170:0'=>array('id'=>170,'data'=>0,'name'=>'Hay Bale','item'=>'hay_block'),
'171:0'=>array('id'=>171,'data'=>0,'name'=>'White Carpet','item'=>'carpet'),
'171:1'=>array('id'=>171,'data'=>1,'name'=>'Orange Carpet','item'=>'carpet'),
'171:2'=>array('id'=>171,'data'=>2,'name'=>'Magenta Carpet','item'=>'carpet'),
'171:3'=>array('id'=>171,'data'=>3,'name'=>'Light Blue Carpet','item'=>'carpet'),
'171:4'=>array('id'=>171,'data'=>4,'name'=>'Yellow Carpet','item'=>'carpet'),
'171:5'=>array('id'=>171,'data'=>5,'name'=>'Lime Carpet','item'=>'carpet'),
'171:6'=>array('id'=>171,'data'=>6,'name'=>'Pink Carpet','item'=>'carpet'),
'171:7'=>array('id'=>171,'data'=>7,'name'=>'Gray Carpet','item'=>'carpet'),
'171:8'=>array('id'=>171,'data'=>8,'name'=>'Light Gray Carpet','item'=>'carpet'),
'171:9'=>array('id'=>171,'data'=>9,'name'=>'Cyan Carpet','item'=>'carpet'),
'171:10'=>array('id'=>171,'data'=>10,'name'=>'Purple Carpet','item'=>'carpet'),
'171:11'=>array('id'=>171,'data'=>11,'name'=>'Blue Carpet','item'=>'carpet'),
'171:12'=>array('id'=>171,'data'=>12,'name'=>'Brown Carpet','item'=>'carpet'),
'171:13'=>array('id'=>171,'data'=>13,'name'=>'Green Carpet','item'=>'carpet'),
'171:14'=>array('id'=>171,'data'=>14,'name'=>'Red Carpet','item'=>'carpet'),
'171:15'=>array('id'=>171,'data'=>15,'name'=>'Black Carpet','item'=>'carpet'),
'172:0'=>array('id'=>172,'data'=>0,'name'=>'Hardened Clay','item'=>'hardened_clay'),
'173:0'=>array('id'=>173,'data'=>0,'name'=>'Block of Coal','item'=>'coal_block'),
'174:0'=>array('id'=>174,'data'=>0,'name'=>'Packed Ice','item'=>'packed_ice'),
'175:0'=>array('id'=>175,'data'=>0,'name'=>'Sunflower','item'=>'double_plant'),
'175:1'=>array('id'=>175,'data'=>1,'name'=>'Lilac','item'=>'double_plant'),
'175:2'=>array('id'=>175,'data'=>2,'name'=>'Double Tallgrass','item'=>'double_plant'),
'175:3'=>array('id'=>175,'data'=>3,'name'=>'Large Fern','item'=>'double_plant'),
'175:4'=>array('id'=>175,'data'=>4,'name'=>'Rose Bush','item'=>'double_plant'),
'175:5'=>array('id'=>175,'data'=>5,'name'=>'Peony','item'=>'double_plant'),
'176:0'=>array('id'=>176,'data'=>0,'name'=>'Free-standing Banner','item'=>'standing_banner'),
'177:0'=>array('id'=>177,'data'=>0,'name'=>'Wall-mounted Banner','item'=>'wall_banner'),
'178:0'=>array('id'=>178,'data'=>0,'name'=>'Inverted Daylight Sensor','item'=>'daylight_detector_inverted'),
'179:0'=>array('id'=>179,'data'=>0,'name'=>'Red Sandstone','item'=>'red_sandstone'),
'179:1'=>array('id'=>179,'data'=>1,'name'=>'Smooth Red Sandstone','item'=>'red_sandstone'),
'179:2'=>array('id'=>179,'data'=>2,'name'=>'Chiseled Red Sandstone','item'=>'red_sandstone'),
'180:0'=>array('id'=>180,'data'=>0,'name'=>'Red Sandstone Stairs','item'=>'red_sandstone_stairs'),
'181:0'=>array('id'=>181,'data'=>0,'name'=>'Double Red Sandstone Slab','item'=>'stone_slab2'),
'182:0'=>array('id'=>182,'data'=>0,'name'=>'Red Sandstone Slab','item'=>'double_stone_slab2'),
'183:0'=>array('id'=>183,'data'=>0,'name'=>'Spruce Fence Gate','item'=>'spruce_fence_gate'),
'184:0'=>array('id'=>184,'data'=>0,'name'=>'Birch Fence Gate','item'=>'birch_fence_gate'),
'185:0'=>array('id'=>185,'data'=>0,'name'=>'Jungle Fence Gate','item'=>'jungle_fence_gate'),
'186:0'=>array('id'=>186,'data'=>0,'name'=>'Dark Oak Fence Gate','item'=>'dark_oak_fence_gate'),
'187:0'=>array('id'=>187,'data'=>0,'name'=>'Acacia Fence Gate','item'=>'acacia_fence_gate'),
'188:0'=>array('id'=>188,'data'=>0,'name'=>'Spruce Fence','item'=>'spruce_fence'),
'189:0'=>array('id'=>189,'data'=>0,'name'=>'Birch Fence','item'=>'birch_fence'),
'190:0'=>array('id'=>190,'data'=>0,'name'=>'Jungle Fence','item'=>'jungle_fence'),
'191:0'=>array('id'=>191,'data'=>0,'name'=>'Dark Oak Fence','item'=>'dark_oak_fence'),
'192:0'=>array('id'=>192,'data'=>0,'name'=>'Acacia Fence','item'=>'acacia_fence'),
'193:0'=>array('id'=>193,'data'=>0,'name'=>'Spruce Door Block','item'=>'spruce_door'),
'194:0'=>array('id'=>194,'data'=>0,'name'=>'Birch Door Block','item'=>'birch_door'),
'195:0'=>array('id'=>195,'data'=>0,'name'=>'Jungle Door Block','item'=>'jungle_door'),
'196:0'=>array('id'=>196,'data'=>0,'name'=>'Acacia Door Block','item'=>'acacia_door'),
'197:0'=>array('id'=>197,'data'=>0,'name'=>'Dark Oak Door Block','item'=>'dark_oak_door'),
'256:0'=>array('id'=>256,'data'=>0,'name'=>'Iron Shovel','item'=>'iron_shovel'),
'257:0'=>array('id'=>257,'data'=>0,'name'=>'Iron Pickaxe','item'=>'iron_pickaxe'),
'258:0'=>array('id'=>258,'data'=>0,'name'=>'Iron Axe','item'=>'iron_axe'),
'259:0'=>array('id'=>259,'data'=>0,'name'=>'Flint and Steel','item'=>'flint_and_steel'),
'260:0'=>array('id'=>260,'data'=>0,'name'=>'Apple','item'=>'apple'),
'261:0'=>array('id'=>261,'data'=>0,'name'=>'Bow','item'=>'bow'),
'262:0'=>array('id'=>262,'data'=>0,'name'=>'Arrow','item'=>'arrow'),
'263:0'=>array('id'=>263,'data'=>0,'name'=>'Coal','item'=>'coal'),
'263:1'=>array('id'=>263,'data'=>1,'name'=>'Charcoal','item'=>'coal'),
'264:0'=>array('id'=>264,'data'=>0,'name'=>'Diamond','item'=>'diamond'),
'265:0'=>array('id'=>265,'data'=>0,'name'=>'Iron Ingot','item'=>'iron_ingot'),
'266:0'=>array('id'=>266,'data'=>0,'name'=>'Gold Ingot','item'=>'gold_ingot'),
'267:0'=>array('id'=>267,'data'=>0,'name'=>'Iron Sword','item'=>'iron_sword'),
'268:0'=>array('id'=>268,'data'=>0,'name'=>'Wooden Sword','item'=>'wooden_sword'),
'269:0'=>array('id'=>269,'data'=>0,'name'=>'Wooden Shovel','item'=>'wooden_shovel'),
'270:0'=>array('id'=>270,'data'=>0,'name'=>'Wooden Pickaxe','item'=>'wooden_pickaxe'),
'271:0'=>array('id'=>271,'data'=>0,'name'=>'Wooden Axe','item'=>'wooden_axe'),
'272:0'=>array('id'=>272,'data'=>0,'name'=>'Stone Sword','item'=>'stone_sword'),
'273:0'=>array('id'=>273,'data'=>0,'name'=>'Stone Shovel','item'=>'stone_shovel'),
'274:0'=>array('id'=>274,'data'=>0,'name'=>'Stone Pickaxe','item'=>'stone_pickaxe'),
'275:0'=>array('id'=>275,'data'=>0,'name'=>'Stone Axe','item'=>'stone_axe'),
'276:0'=>array('id'=>276,'data'=>0,'name'=>'Diamond Sword','item'=>'diamond_sword'),
'277:0'=>array('id'=>277,'data'=>0,'name'=>'Diamond Shovel','item'=>'diamond_shovel'),
'278:0'=>array('id'=>278,'data'=>0,'name'=>'Diamond Pickaxe','item'=>'diamond_pickaxe'),
'279:0'=>array('id'=>279,'data'=>0,'name'=>'Diamond Axe','item'=>'diamond_axe'),
'280:0'=>array('id'=>280,'data'=>0,'name'=>'Stick','item'=>'stick'),
'281:0'=>array('id'=>281,'data'=>0,'name'=>'Bowl','item'=>'bowl'),
'282:0'=>array('id'=>282,'data'=>0,'name'=>'Mushroom Stew','item'=>'mushroom_stew'),
'283:0'=>array('id'=>283,'data'=>0,'name'=>'Golden Sword','item'=>'golden_sword'),
'284:0'=>array('id'=>284,'data'=>0,'name'=>'Golden Shovel','item'=>'golden_shovel'),
'285:0'=>array('id'=>285,'data'=>0,'name'=>'Golden Pickaxe','item'=>'golden_pickaxe'),
'286:0'=>array('id'=>286,'data'=>0,'name'=>'Golden Axe','item'=>'golden_axe'),
'287:0'=>array('id'=>287,'data'=>0,'name'=>'String','item'=>'string'),
'288:0'=>array('id'=>288,'data'=>0,'name'=>'Feather','item'=>'feather'),
'289:0'=>array('id'=>289,'data'=>0,'name'=>'Gunpowder','item'=>'gunpowder'),
'290:0'=>array('id'=>290,'data'=>0,'name'=>'Wooden Hoe','item'=>'wooden_hoe'),
'291:0'=>array('id'=>291,'data'=>0,'name'=>'Stone Hoe','item'=>'stone_hoe'),
'292:0'=>array('id'=>292,'data'=>0,'name'=>'Iron Hoe','item'=>'iron_hoe'),
'293:0'=>array('id'=>293,'data'=>0,'name'=>'Diamond Hoe','item'=>'diamond_hoe'),
'294:0'=>array('id'=>294,'data'=>0,'name'=>'Golden Hoe','item'=>'golden_hoe'),
'295:0'=>array('id'=>295,'data'=>0,'name'=>'Wheat Seeds','item'=>'wheat_seeds'),
'296:0'=>array('id'=>296,'data'=>0,'name'=>'Wheat','item'=>'wheat'),
'297:0'=>array('id'=>297,'data'=>0,'name'=>'Bread','item'=>'bread'),
'298:0'=>array('id'=>298,'data'=>0,'name'=>'Leather Helmet','item'=>'leather_helmet'),
'299:0'=>array('id'=>299,'data'=>0,'name'=>'Leather Tunic','item'=>'leather_chestplate'),
'300:0'=>array('id'=>300,'data'=>0,'name'=>'Leather Pants','item'=>'leather_leggings'),
'301:0'=>array('id'=>301,'data'=>0,'name'=>'Leather Boots','item'=>'leather_boots'),
'302:0'=>array('id'=>302,'data'=>0,'name'=>'Chainmail Helmet','item'=>'chainmail_helmet'),
'303:0'=>array('id'=>303,'data'=>0,'name'=>'Chainmail Chestplate','item'=>'chainmail_chestplate'),
'304:0'=>array('id'=>304,'data'=>0,'name'=>'Chainmail Leggings','item'=>'chainmail_leggings'),
'305:0'=>array('id'=>305,'data'=>0,'name'=>'Chainmail Boots','item'=>'chainmail_boots'),
'306:0'=>array('id'=>306,'data'=>0,'name'=>'Iron Helmet','item'=>'iron_helmet'),
'307:0'=>array('id'=>307,'data'=>0,'name'=>'Iron Chestplate','item'=>'iron_chestplate'),
'308:0'=>array('id'=>308,'data'=>0,'name'=>'Iron Leggings','item'=>'iron_leggings'),
'309:0'=>array('id'=>309,'data'=>0,'name'=>'Iron Boots','item'=>'iron_boots'),
'310:0'=>array('id'=>310,'data'=>0,'name'=>'Diamond Helmet','item'=>'diamond_helmet'),
'311:0'=>array('id'=>311,'data'=>0,'name'=>'Diamond Chestplate','item'=>'diamond_chestplate'),
'312:0'=>array('id'=>312,'data'=>0,'name'=>'Diamond Leggings','item'=>'diamond_leggings'),
'313:0'=>array('id'=>313,'data'=>0,'name'=>'Diamond Boots','item'=>'diamond_boots'),
'314:0'=>array('id'=>314,'data'=>0,'name'=>'Golden Helmet','item'=>'golden_helmet'),
'315:0'=>array('id'=>315,'data'=>0,'name'=>'Golden Chestplate','item'=>'golden_chestplate'),
'316:0'=>array('id'=>316,'data'=>0,'name'=>'Golden Leggings','item'=>'golden_leggings'),
'317:0'=>array('id'=>317,'data'=>0,'name'=>'Golden Boots','item'=>'golden_boots'),
'318:0'=>array('id'=>318,'data'=>0,'name'=>'Flint','item'=>'flint_and_steel'),
'319:0'=>array('id'=>319,'data'=>0,'name'=>'Raw Porkchop','item'=>'porkchop'),
'320:0'=>array('id'=>320,'data'=>0,'name'=>'Cooked Porkchop','item'=>'cooked_porkchop'),
'321:0'=>array('id'=>321,'data'=>0,'name'=>'Painting','item'=>'painting'),
'322:0'=>array('id'=>322,'data'=>0,'name'=>'Golden Apple','item'=>'golden_apple'),
'322:1'=>array('id'=>322,'data'=>1,'name'=>'Enchanted Golden Apple','item'=>'golden_apple'),
'323:0'=>array('id'=>323,'data'=>0,'name'=>'Sign','item'=>'sign'),
'324:0'=>array('id'=>324,'data'=>0,'name'=>'Oak Door','item'=>'wooden_door'),
'325:0'=>array('id'=>325,'data'=>0,'name'=>'Bucket','item'=>'bucket'),
'326:0'=>array('id'=>326,'data'=>0,'name'=>'Water Bucket','item'=>'water_bucket'),
'327:0'=>array('id'=>327,'data'=>0,'name'=>'Lava Bucket','item'=>'lava_bucket'),
'328:0'=>array('id'=>328,'data'=>0,'name'=>'Minecart','item'=>'minecart'),
'329:0'=>array('id'=>329,'data'=>0,'name'=>'Saddle','item'=>'saddle'),
'330:0'=>array('id'=>330,'data'=>0,'name'=>'Iron Door','item'=>'iron_door'),
'331:0'=>array('id'=>331,'data'=>0,'name'=>'Redstone','item'=>'redstone'),
'332:0'=>array('id'=>332,'data'=>0,'name'=>'Snowball','item'=>'snowball'),
'333:0'=>array('id'=>333,'data'=>0,'name'=>'Boat','item'=>'boat'),
'334:0'=>array('id'=>334,'data'=>0,'name'=>'Leather','item'=>'leather'),
'335:0'=>array('id'=>335,'data'=>0,'name'=>'Milk Bucket','item'=>'milk_bucket'),
'336:0'=>array('id'=>336,'data'=>0,'name'=>'Brick','item'=>'brick'),
'337:0'=>array('id'=>337,'data'=>0,'name'=>'Clay','item'=>'clay_ball'),
'338:0'=>array('id'=>338,'data'=>0,'name'=>'Sugar Canes','item'=>'reeds'),
'339:0'=>array('id'=>339,'data'=>0,'name'=>'Paper','item'=>'paper'),
'340:0'=>array('id'=>340,'data'=>0,'name'=>'Book','item'=>'book'),
'341:0'=>array('id'=>341,'data'=>0,'name'=>'Slimeball','item'=>'slime_ball'),
'342:0'=>array('id'=>342,'data'=>0,'name'=>'Minecart with Chest','item'=>'chest_minecart'),
'343:0'=>array('id'=>343,'data'=>0,'name'=>'Minecart with Furnace','item'=>'furnace_minecart'),
'344:0'=>array('id'=>344,'data'=>0,'name'=>'Egg','item'=>'egg'),
'345:0'=>array('id'=>345,'data'=>0,'name'=>'Compass','item'=>'compass'),
'346:0'=>array('id'=>346,'data'=>0,'name'=>'Fishing Rod','item'=>'fishing_rod'),
'347:0'=>array('id'=>347,'data'=>0,'name'=>'Clock','item'=>'clock'),
'348:0'=>array('id'=>348,'data'=>0,'name'=>'Glowstone Dust','item'=>'glowstone_dust'),
'349:0'=>array('id'=>349,'data'=>0,'name'=>'Raw Fish','item'=>'fish'),
'349:1'=>array('id'=>349,'data'=>1,'name'=>'Raw Salmon','item'=>'fish'),
'349:2'=>array('id'=>349,'data'=>2,'name'=>'Clownfish','item'=>'fish'),
'349:3'=>array('id'=>349,'data'=>3,'name'=>'Pufferfish','item'=>'fish'),
'350:0'=>array('id'=>350,'data'=>0,'name'=>'Cooked Fish','item'=>'cooked_fish'),
'350:1'=>array('id'=>350,'data'=>1,'name'=>'Cooked Salmon','item'=>'cooked_fish'),
'351:0'=>array('id'=>351,'data'=>0,'name'=>'Ink Sack','item'=>'dye'),
'351:1'=>array('id'=>351,'data'=>1,'name'=>'Rose Red','item'=>'dye'),
'351:2'=>array('id'=>351,'data'=>2,'name'=>'Cactus Green','item'=>'dye'),
'351:3'=>array('id'=>351,'data'=>3,'name'=>'Coco Beans','item'=>'dye'),
'351:4'=>array('id'=>351,'data'=>4,'name'=>'Lapis Lazuli','item'=>'dye'),
'351:5'=>array('id'=>351,'data'=>5,'name'=>'Purple Dye','item'=>'dye'),
'351:6'=>array('id'=>351,'data'=>6,'name'=>'Cyan Dye','item'=>'dye'),
'351:7'=>array('id'=>351,'data'=>7,'name'=>'Light Gray Dye','item'=>'dye'),
'351:8'=>array('id'=>351,'data'=>8,'name'=>'Gray Dye','item'=>'dye'),
'351:9'=>array('id'=>351,'data'=>9,'name'=>'Pink Dye','item'=>'dye'),
'351:10'=>array('id'=>351,'data'=>10,'name'=>'Lime Dye','item'=>'dye'),
'351:11'=>array('id'=>351,'data'=>11,'name'=>'Dandelion Yellow','item'=>'dye'),
'351:12'=>array('id'=>351,'data'=>12,'name'=>'Light Blue Dye','item'=>'dye'),
'351:13'=>array('id'=>351,'data'=>13,'name'=>'Magenta Dye','item'=>'dye'),
'351:14'=>array('id'=>351,'data'=>14,'name'=>'Orange Dye','item'=>'dye'),
'351:15'=>array('id'=>351,'data'=>15,'name'=>'Bone Meal','item'=>'dye'),
'352:0'=>array('id'=>352,'data'=>0,'name'=>'Bone','item'=>'bone'),
'353:0'=>array('id'=>353,'data'=>0,'name'=>'Sugar','item'=>'sugar'),
'354:0'=>array('id'=>354,'data'=>0,'name'=>'Cake','item'=>'cake'),
'355:0'=>array('id'=>355,'data'=>0,'name'=>'Bed','item'=>'bed'),
'356:0'=>array('id'=>356,'data'=>0,'name'=>'Redstone Repeater','item'=>'repeater'),
'357:0'=>array('id'=>357,'data'=>0,'name'=>'Cookie','item'=>'cookie'),
'358:0'=>array('id'=>358,'data'=>0,'name'=>'Map','item'=>'filled_map'),
'359:0'=>array('id'=>359,'data'=>0,'name'=>'Shears','item'=>'shears'),
'360:0'=>array('id'=>360,'data'=>0,'name'=>'Melon','item'=>'melon'),
'361:0'=>array('id'=>361,'data'=>0,'name'=>'Pumpkin Seeds','item'=>'pumpkin_seeds'),
'362:0'=>array('id'=>362,'data'=>0,'name'=>'Melon Seeds','item'=>'melon_seeds'),
'363:0'=>array('id'=>363,'data'=>0,'name'=>'Raw Beef','item'=>'beef'),
'364:0'=>array('id'=>364,'data'=>0,'name'=>'Steak','item'=>'cooked_beef'),
'365:0'=>array('id'=>365,'data'=>0,'name'=>'Raw Chicken','item'=>'chicken'),
'366:0'=>array('id'=>366,'data'=>0,'name'=>'Cooked Chicken','item'=>'cooked_chicken'),
'367:0'=>array('id'=>367,'data'=>0,'name'=>'Rotten Flesh','item'=>'rotten_flesh'),
'368:0'=>array('id'=>368,'data'=>0,'name'=>'Ender Pearl','item'=>'ender_pearl'),
'369:0'=>array('id'=>369,'data'=>0,'name'=>'Blaze Rod','item'=>'blaze_rod'),
'370:0'=>array('id'=>370,'data'=>0,'name'=>'Ghast Tear','item'=>'ghast_tear'),
'371:0'=>array('id'=>371,'data'=>0,'name'=>'Gold Nugget','item'=>'gold_nugget'),
'372:0'=>array('id'=>372,'data'=>0,'name'=>'Nether Wart','item'=>'nether_wart'),
'373:0'=>array('id'=>373,'data'=>0,'name'=>'Potion','item'=>'potion'),
'374:0'=>array('id'=>374,'data'=>0,'name'=>'Glass Bottle','item'=>'glass_bottle'),
'375:0'=>array('id'=>375,'data'=>0,'name'=>'Spider Eye','item'=>'spider_eye'),
'376:0'=>array('id'=>376,'data'=>0,'name'=>'Fermented Spider Eye','item'=>'fermented_spider_eye'),
'377:0'=>array('id'=>377,'data'=>0,'name'=>'Blaze Powder','item'=>'blaze_powder'),
'378:0'=>array('id'=>378,'data'=>0,'name'=>'Magma Cream','item'=>'magma_cream'),
'379:0'=>array('id'=>379,'data'=>0,'name'=>'Brewing Stand','item'=>'brewing_stand'),
'380:0'=>array('id'=>380,'data'=>0,'name'=>'Cauldron','item'=>'cauldron'),
'381:0'=>array('id'=>381,'data'=>0,'name'=>'Eye of Ender','item'=>'ender_eye'),
'382:0'=>array('id'=>382,'data'=>0,'name'=>'Glistering Melon','item'=>'speckled_melon'),
'383:50'=>array('id'=>383,'data'=>50,'name'=>'Spawn Creeper','item'=>'spawn_egg'),
'383:51'=>array('id'=>383,'data'=>51,'name'=>'Spawn Skeleton','item'=>'spawn_egg'),
'383:52'=>array('id'=>383,'data'=>52,'name'=>'Spawn Spider','item'=>'spawn_egg'),
'383:54'=>array('id'=>383,'data'=>54,'name'=>'Spawn Zombie','item'=>'spawn_egg'),
'383:55'=>array('id'=>383,'data'=>55,'name'=>'Spawn Slime','item'=>'spawn_egg'),
'383:56'=>array('id'=>383,'data'=>56,'name'=>'Spawn Ghast','item'=>'spawn_egg'),
'383:57'=>array('id'=>383,'data'=>57,'name'=>'Spawn Pigman','item'=>'spawn_egg'),
'383:58'=>array('id'=>383,'data'=>58,'name'=>'Spawn Enderman','item'=>'spawn_egg'),
'383:59'=>array('id'=>383,'data'=>59,'name'=>'Spawn Cave Spider','item'=>'spawn_egg'),
'383:60'=>array('id'=>383,'data'=>60,'name'=>'Spawn Silverfish','item'=>'spawn_egg'),
'383:61'=>array('id'=>383,'data'=>61,'name'=>'Spawn Blaze','item'=>'spawn_egg'),
'383:62'=>array('id'=>383,'data'=>62,'name'=>'Spawn Magma Cube','item'=>'spawn_egg'),
'383:65'=>array('id'=>383,'data'=>65,'name'=>'Spawn Bat','item'=>'spawn_egg'),
'383:66'=>array('id'=>383,'data'=>66,'name'=>'Spawn Witch','item'=>'spawn_egg'),
'383:67'=>array('id'=>383,'data'=>67,'name'=>'Spawn Endermite','item'=>'spawn_egg'),
'383:68'=>array('id'=>383,'data'=>68,'name'=>'Spawn Guardian','item'=>'spawn_egg'),
'383:90'=>array('id'=>383,'data'=>90,'name'=>'Spawn Pig','item'=>'spawn_egg'),
'383:91'=>array('id'=>383,'data'=>91,'name'=>'Spawn Sheep','item'=>'spawn_egg'),
'383:92'=>array('id'=>383,'data'=>92,'name'=>'Spawn Cow','item'=>'spawn_egg'),
'383:93'=>array('id'=>383,'data'=>93,'name'=>'Spawn Chicken','item'=>'spawn_egg'),
'383:94'=>array('id'=>383,'data'=>94,'name'=>'Spawn Squid','item'=>'spawn_egg'),
'383:95'=>array('id'=>383,'data'=>95,'name'=>'Spawn Wolf','item'=>'spawn_egg'),
'383:96'=>array('id'=>383,'data'=>96,'name'=>'Spawn Mooshroom','item'=>'spawn_egg'),
'383:98'=>array('id'=>383,'data'=>98,'name'=>'Spawn Ocelot','item'=>'spawn_egg'),
'383:100'=>array('id'=>383,'data'=>100,'name'=>'Spawn Horse','item'=>'spawn_egg'),
'383:101'=>array('id'=>383,'data'=>101,'name'=>'Spawn Rabbit','item'=>'spawn_egg'),
'383:120'=>array('id'=>383,'data'=>120,'name'=>'Spawn Villager','item'=>'spawn_egg'),
'384:0'=>array('id'=>384,'data'=>0,'name'=>'Bottle o\' Enchanting','item'=>'experience_bottle'),
'385:0'=>array('id'=>385,'data'=>0,'name'=>'Fire Charge','item'=>'fire_charge'),
'386:0'=>array('id'=>386,'data'=>0,'name'=>'Book and Quill','item'=>'writable_book'),
'387:0'=>array('id'=>387,'data'=>0,'name'=>'Written Book','item'=>'written_book'),
'388:0'=>array('id'=>388,'data'=>0,'name'=>'Emerald','item'=>'emerald'),
'389:0'=>array('id'=>389,'data'=>0,'name'=>'Item Frame','item'=>'item_frame'),
'390:0'=>array('id'=>390,'data'=>0,'name'=>'Flower Pot','item'=>'flower_pot'),
'391:0'=>array('id'=>391,'data'=>0,'name'=>'Carrot','item'=>'carrot'),
'392:0'=>array('id'=>392,'data'=>0,'name'=>'Potato','item'=>'potato'),
'393:0'=>array('id'=>393,'data'=>0,'name'=>'Baked Potato','item'=>'baked_potato'),
'394:0'=>array('id'=>394,'data'=>0,'name'=>'Poisonous Potato','item'=>'poisonous_potato'),
'395:0'=>array('id'=>395,'data'=>0,'name'=>'Empty Map','item'=>'map'),
'396:0'=>array('id'=>396,'data'=>0,'name'=>'Golden Carrot','item'=>'golden_carrot'),
'397:0'=>array('id'=>397,'data'=>0,'name'=>'Mob Head (Skeleton)','item'=>'skull'),
'397:1'=>array('id'=>397,'data'=>1,'name'=>'Mob Head (Wither Skeleton)','item'=>'skull'),
'397:2'=>array('id'=>397,'data'=>2,'name'=>'Mob Head (Zombie)','item'=>'skull'),
'397:3'=>array('id'=>397,'data'=>3,'name'=>'Mob Head (Human)','item'=>'skull'),
'397:4'=>array('id'=>397,'data'=>4,'name'=>'Mob Head (Creeper)','item'=>'skull'),
'398:0'=>array('id'=>398,'data'=>0,'name'=>'Carrot on a Stick','item'=>'carrot_on_a_stick'),
'399:0'=>array('id'=>399,'data'=>0,'name'=>'Nether Star','item'=>'nether_star'),
'400:0'=>array('id'=>400,'data'=>0,'name'=>'Pumpkin Pie','item'=>'pumpkin_pie'),
'401:0'=>array('id'=>401,'data'=>0,'name'=>'Firework Rocket','item'=>'fireworks'),
'402:0'=>array('id'=>402,'data'=>0,'name'=>'Firework Star','item'=>'firework_charge'),
'403:0'=>array('id'=>403,'data'=>0,'name'=>'Enchanted Book','item'=>'enchanted_book'),
'404:0'=>array('id'=>404,'data'=>0,'name'=>'Redstone Comparator','item'=>'comparator'),
'405:0'=>array('id'=>405,'data'=>0,'name'=>'Nether Brick','item'=>'netherbrick'),
'406:0'=>array('id'=>406,'data'=>0,'name'=>'Nether Quartz','item'=>'quartz'),
'407:0'=>array('id'=>407,'data'=>0,'name'=>'Minecart with TNT','item'=>'tnt_minecart'),
'408:0'=>array('id'=>408,'data'=>0,'name'=>'Minecart with Hopper','item'=>'hopper_minecart'),
'409:0'=>array('id'=>409,'data'=>0,'name'=>'Prismarine Shard','item'=>'prismarine_shard'),
'410:0'=>array('id'=>410,'data'=>0,'name'=>'Prismarine Crystals','item'=>'prismarine_crystals'),
'411:0'=>array('id'=>411,'data'=>0,'name'=>'Raw Rabbit','item'=>'rabbit'),
'412:0'=>array('id'=>412,'data'=>0,'name'=>'Cooked Rabbit','item'=>'cooked_rabbit'),
'413:0'=>array('id'=>413,'data'=>0,'name'=>'Rabbit Stew','item'=>'rabbit_stew'),
'414:0'=>array('id'=>414,'data'=>0,'name'=>'Rabbit\'s Foot','item'=>'rabbit_foot'),
'415:0'=>array('id'=>415,'data'=>0,'name'=>'Rabbit Hide','item'=>'rabbit_hide'),
'416:0'=>array('id'=>416,'data'=>0,'name'=>'Armor Stand','item'=>'armor_stand'),
'417:0'=>array('id'=>417,'data'=>0,'name'=>'Iron Horse Armor','item'=>'iron_horse_armor'),
'418:0'=>array('id'=>418,'data'=>0,'name'=>'Golden Horse Armor','item'=>'golden_horse_armor'),
'419:0'=>array('id'=>419,'data'=>0,'name'=>'Diamond Horse Armor','item'=>'diamond_horse_armor'),
'420:0'=>array('id'=>420,'data'=>0,'name'=>'Lead','item'=>'lead'),
'421:0'=>array('id'=>421,'data'=>0,'name'=>'Name Tag','item'=>'name_tag'),
'422:0'=>array('id'=>422,'data'=>0,'name'=>'Minecart with Command Block','item'=>'command_block_minecart'),
'423:0'=>array('id'=>423,'data'=>0,'name'=>'Raw Mutton','item'=>'mutton'),
'424:0'=>array('id'=>424,'data'=>0,'name'=>'Cooked Mutton','item'=>'cooked_mutton'),
'425:0'=>array('id'=>425,'data'=>0,'name'=>'Banner','item'=>'banner'),
'427:0'=>array('id'=>427,'data'=>0,'name'=>'Spruce Door','item'=>'spruce_door'),
'428:0'=>array('id'=>428,'data'=>0,'name'=>'Birch Door','item'=>'birch_door'),
'429:0'=>array('id'=>429,'data'=>0,'name'=>'Jungle Door','item'=>'jungle_door'),
'430:0'=>array('id'=>430,'data'=>0,'name'=>'Acacia Door','item'=>'acacia_door'),
'431:0'=>array('id'=>431,'data'=>0,'name'=>'Dark Oak Door','item'=>'dark_oak_door'),
'2256:0'=>array('id'=>2256,'data'=>0,'name'=>'13 Disc','item'=>'record_13'),
'2257:0'=>array('id'=>2257,'data'=>0,'name'=>'Cat Disc','item'=>'record_cat'),
'2258:0'=>array('id'=>2258,'data'=>0,'name'=>'Blocks Disc','item'=>'record_blocks'),
'2259:0'=>array('id'=>2259,'data'=>0,'name'=>'Chirp Disc','item'=>'record_chirp'),
'2260:0'=>array('id'=>2260,'data'=>0,'name'=>'Far Disc','item'=>'record_far'),
'2261:0'=>array('id'=>2261,'data'=>0,'name'=>'Mall Disc','item'=>'record_mall'),
'2262:0'=>array('id'=>2262,'data'=>0,'name'=>'Mellohi Disc','item'=>'record_mellohi'),
'2263:0'=>array('id'=>2263,'data'=>0,'name'=>'Stal Disc','item'=>'record_stal'),
'2264:0'=>array('id'=>2264,'data'=>0,'name'=>'Strad Disc','item'=>'record_strad'),
'2265:0'=>array('id'=>2265,'data'=>0,'name'=>'Ward Disc','item'=>'record_ward'),
'2266:0'=>array('id'=>2266,'data'=>0,'name'=>'11 Disc','item'=>'record_11'),
'2267:0'=>array('id'=>2267,'data'=>0,'name'=>'Wait Disc','item'=>'record_wait'),
);
